# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/giulia/setup-makefiles.sh

# Include vendor blobs
$(call inherit-product, vendor/oneplus/giulia/giulia-vendor-blobs.mk)

# Soong namespaces
PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/giulia

# Properties
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.qti.va_aosp.support=1 \
    ro.vendor.qti.va_odm.support=1 \
    ro.vendor.perf.scroll_opt=true \
    persist.vendor.qcom.bluetooth.enable.splita2dp=true \
    persist.vendor.qcom.bluetooth.a2dp_offload_cap=sbc-aptx-aptxtws-aptxhd-aac-ldac \
    persist.vendor.qcom.bluetooth.aac_frm_ctl.enabled=true \
    persist.vendor.qcom.bluetooth.twsp_state.enabled=false \
    persist.vendor.qcom.bluetooth.scram.enabled=true \
    persist.vendor.qcom.bluetooth.aac_vbr_ctl.enabled=false \
    persist.vendor.radio.enableadvancedscan=true \
    persist.vendor.radio.apm_sim_not_pwdn=1 \
    persist.vendor.radio.sib16_support=1 \
    persist.vendor.radio.custom_ecc=1 \
    persist.vendor.radio.procedure_bytes=SKIP \
    persist.vendor.radio.rat_on=combine \
    persist.vendor.usb.config=mtp,adb \
    persist.vendor.qcom.bluetooth.enable.splita2dp=true \
    persist.vendor.camera.privapp.list=org.codeaurora.snapcam \
    persist.vendor.cne.feature=1 \
    persist.vendor.data.mode=concurrent \
    persist.vendor.overlay.izat.optin=rro

# Audio
PRODUCT_PACKAGES += \
    android.hardware.audio.service \
    android.hardware.audio@7.0-impl \
    android.hardware.audio.effect@7.0-impl \
    android.hardware.soundtrigger@2.3-impl

# Bluetooth
PRODUCT_PACKAGES += \
    android.hardware.bluetooth@1.1-service-qti \
    android.hardware.bluetooth.audio-impl \
    vendor.qti.hardware.bluetooth_audio@2.1-impl \
    vendor.qti.hardware.btconfigstore@1.0.vendor \
    vendor.qti.hardware.btconfigstore@2.0.vendor

# Camera
PRODUCT_PACKAGES += \
    android.hardware.camera.provider@2.4-impl \
    android.hardware.camera.provider@2.4-service_64 \
    vendor.qti.hardware.camera.device@1.0.vendor \
    vendor.qti.hardware.camera.postproc@1.0.vendor

# Display
PRODUCT_PACKAGES += \
    android.hardware.graphics.composer@2.4-service \
    android.hardware.graphics.mapper@3.0-impl-qti-display \
    android.hardware.graphics.mapper@4.0-impl-qti-display \
    android.hardware.memtrack@1.0-impl \
    android.hardware.memtrack@1.0-service

# DRM
PRODUCT_PACKAGES += \
    android.hardware.drm@1.4-service.clearkey

# Gatekeeper
PRODUCT_PACKAGES += \
    android.hardware.gatekeeper@1.0-impl \
    android.hardware.gatekeeper@1.0-service

# GPS
PRODUCT_PACKAGES += \
    android.hardware.gnss@2.1-impl-qti \
    android.hardware.gnss@2.1-service-qti

# Health
PRODUCT_PACKAGES += \
    android.hardware.health@2.1-impl \
    android.hardware.health@2.1-service

# Keymaster
PRODUCT_PACKAGES += \
    android.hardware.keymaster@4.1-service-qti

# Media
PRODUCT_PACKAGES += \
    android.hardware.media.omx@1.0-impl \
    android.hardware.media.omx@1.0-service

# Neural Networks
PRODUCT_PACKAGES += \
    android.hardware.neuralnetworks@1.3-service-qti

# Power
PRODUCT_PACKAGES += \
    android.hardware.power-service-qti

# RIL
PRODUCT_PACKAGES += \
    android.hardware.radio@1.6 \
    android.hardware.radio.config@1.3 \
    android.hardware.radio.deprecated@1.0 \
    android.hardware.secure_element@1.2 \
    android.system.net.netd@1.1

# Sensors
PRODUCT_PACKAGES += \
    android.hardware.sensors@2.1-service.multihal \
    android.frameworks.sensorservice@1.0

# USB
PRODUCT_PACKAGES += \
    android.hardware.usb@1.3-service-qti

# WiFi
PRODUCT_PACKAGES += \
    android.hardware.wifi@1.0-service \
    android.hardware.wifi.supplicant@1.4 \
    android.hardware.wifi.hostapd@1.3

# AAPT
PRODUCT_AAPT_CONFIG := normal
PRODUCT_AAPT_PREF_CONFIG := xxhdpi

# Boot animation
TARGET_SCREEN_HEIGHT := 2780
TARGET_SCREEN_WIDTH := 1264

# Essential Hardware Components
PRODUCT_PACKAGES += \
    TimeService \
    IWlanService \
    CneApp \
    android.hardware.sensors-service.multihal

# Essential Vendor Libraries
PRODUCT_PACKAGES += \
    libQnnHtp \
    libQnnSystem \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.7 \
    vendor.qti.hardware.radio.ims@1.9 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.perf@2.3 \
    vendor.qti.hardware.bluetooth_audio@2.1

# Standard Android Permissions
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.bluetooth.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth.xml \
    frameworks/native/data/etc/android.hardware.bluetooth_le.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth_le.xml \
    frameworks/native/data/etc/android.hardware.camera.flash-autofocus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    frameworks/native/data/etc/android.hardware.camera.front.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.front.xml \
    frameworks/native/data/etc/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.fingerprint.xml

# Generic Device Info (minimal required for build)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.hardware.nfc_nci=nqx.default \
    ro.hardware.keystore_desede=true \
    ro.hardware.vulkan=adreno \
    ro.hardware.egl=adreno \
    ro.soc.manufacturer=QTI

# Security Patch Level
VENDOR_SECURITY_PATCH := 2024-01-05

# Copy all Oneplus-specific proprietary libraries to target location
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/etc/wifi/sar-vendor-cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/sar-vendor-cmd.xml \
    vendor/oneplus/giulia/proprietary/vendor/bin/qcc-vendor:$(TARGET_COPY_OUT_VENDOR)/bin/qcc-vendor \
    vendor/oneplus/giulia/proprietary/vendor/etc/flags.prop:$(TARGET_COPY_OUT_VENDOR)/etc/flags.prop \
    vendor/oneplus/giulia/proprietary/vendor/etc/property_list.prop:$(TARGET_COPY_OUT_VENDOR)/etc/property_list.prop

# Include firmware files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b01 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b02 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b03 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b04 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b05 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b06 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b07 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.mdt \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/antdtx.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/antdtx.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/antdtx.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/antdtx.b01 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b05

# Include DSP files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/dsp/adsp/fastrpc_shell_3:$(TARGET_COPY_OUT_VENDOR)/dsp/adsp/fastrpc_shell_3 \
    vendor/oneplus/giulia/proprietary/vendor/dsp/cdsp/fastrpc_shell_3:$(TARGET_COPY_OUT_VENDOR)/dsp/cdsp/fastrpc_shell_3

# Include vibrator configuration files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/etc/vibrator_service_config:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator_service_config \
    vendor/oneplus/giulia/proprietary/vendor/etc/vibrator/vibrator_customized_effect.json:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/vibrator_customized_effect.json \
    vendor/oneplus/giulia/proprietary/vendor/etc/vibrator/vibrator_effect.json:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/vibrator_effect.json \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vibrator-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vibrator-default.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/init/vibrator-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vibrator-default.rc

# Additional modules or packages specific to this device
PRODUCT_PACKAGES += \
    CACertService

# Vibrator and fingerprint libraries
PRODUCT_PACKAGES += \
    android.hardware.vibrator-V2-ndk \
    libaacvibrator \
    liboplusvibratoreffect \
    vendor.oplus.hardware.vibrator-V1-ndk \
    vendor.oplus.hardware.biometrics.fingerprint \
    libudfps_extension.oneplus

# Add proprietary permissions
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.biometrics.face.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.biometrics.face.xml \
    frameworks/native/data/etc/android.hardware.biometrics.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.biometrics.fingerprint.xml

# OnePlus 13R / Giulia device identifiers
PRODUCT_MODEL := CPH2691
PRODUCT_SYSTEM_NAME := OnePlus13R
PRODUCT_SYSTEM_DEVICE := OP5D3BL1
PRODUCT_GMS_CLIENTID_BASE := android-oneplus

# Device-specific properties
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.build.fingerprint=OnePlus/CPH2691IN/OP5D3BL1:15/UKQ1.231108.001/V.R4T3.1cff019-3eb5-3eb4:user/release-keys \
    ro.product.vendor.brand=oneplus \
    ro.product.vendor.device=giulia \
    ro.product.vendor.manufacturer=oneplus \
    ro.product.vendor.model=CPH2691 \
    ro.product.vendor.name=OnePlus13R \
    ro.product.board=pineapple \
    ro.soc.manufacturer=QTI

# Prebuilt APKs
PRODUCT_PACKAGES += \
    qcrilmsgtunnel

# Vendor libraries
PRODUCT_PACKAGES += \
    vendor.oplus.hardware.charger@1.0 \
    vendor.oplus.hardware.performance@2.0

# Copy critical proprietary firmware and hardware-specific files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.mdt \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b05

# Critical proprietary hardware components
PRODUCT_PACKAGES += \
    qcrilmsgtunnel

# Essential vendor libraries
PRODUCT_PACKAGES += \
    vendor.oplus.hardware.charger@1.0 \
    vendor.oplus.hardware.biometrics.fingerprint

# Device identifiers
PRODUCT_MODEL := CPH2691
PRODUCT_SYSTEM_NAME := OnePlus13R
PRODUCT_SYSTEM_DEVICE := OP5D3BL1

# Remove OnePlus-specific overlays
PRODUCT_PACKAGE_OVERLAYS := 

# Essential Packages (non-OnePlus specific)
PRODUCT_PACKAGES += \
    TimeService \
    IWlanService \
    CneApp

# Essential Properties (non-OnePlus specific)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.hardware.nfc_nci=nqx.default \
    ro.hardware.keystore_desede=true \
    ro.hardware.vulkan=adreno \
    ro.hardware.egl=adreno

# Include product binaries
$(call inherit-product, vendor/oneplus/giulia/giulia-vendor-blobs.mk)

# Include essential vendor blobs
$(call inherit-product, vendor/oneplus/giulia/giulia-vendor-blobs.mk)

# Essential Packages (non-OnePlus specific)
PRODUCT_PACKAGES += \
    TimeService \
    IWlanService \
    CneApp

# Remove OnePlus-specific overlays
PRODUCT_PACKAGE_OVERLAYS := 

# Essential Properties (non-OnePlus specific)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.hardware.nfc_nci=nqx.default \
    ro.hardware.keystore_desede=true \
    ro.hardware.vulkan=adreno \
    ro.hardware.egl=adreno

# Standard Android Security Patch
VENDOR_SECURITY_PATCH := 2024-01-05 