# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/giulia/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/oneplus/giulia

# AAPT
PRODUCT_AAPT_CONFIG := normal
PRODUCT_AAPT_PREF_CONFIG := xxhdpi

# Boot animation
TARGET_SCREEN_HEIGHT := 2780
TARGET_SCREEN_WIDTH := 1264

# Copy all Oneplus-specific proprietary libraries to target location
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/etc/wifi/sar-vendor-cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/sar-vendor-cmd.xml \
    vendor/oneplus/giulia/proprietary/vendor/bin/qcc-vendor:$(TARGET_COPY_OUT_VENDOR)/bin/qcc-vendor \
    vendor/oneplus/giulia/proprietary/vendor/etc/flags.prop:$(TARGET_COPY_OUT_VENDOR)/etc/flags.prop \
    vendor/oneplus/giulia/proprietary/vendor/etc/property_list.prop:$(TARGET_COPY_OUT_VENDOR)/etc/property_list.prop

# Include firmware files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b01 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b02 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b03 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b04 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b05 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b06 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.b07 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.mdt \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/antdtx.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/antdtx.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/antdtx.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/antdtx.b01 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b05

# Include DSP files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/dsp/adsp/fastrpc_shell_3:$(TARGET_COPY_OUT_VENDOR)/dsp/adsp/fastrpc_shell_3 \
    vendor/oneplus/giulia/proprietary/vendor/dsp/adsp/fastrpc_shell_unsigned_3:$(TARGET_COPY_OUT_VENDOR)/dsp/adsp/fastrpc_shell_unsigned_3 \
    vendor/oneplus/giulia/proprietary/vendor/dsp/cdsp/fastrpc_shell_3:$(TARGET_COPY_OUT_VENDOR)/dsp/cdsp/fastrpc_shell_3 \
    vendor/oneplus/giulia/proprietary/vendor/dsp/cdsp/fastrpc_shell_unsigned_3:$(TARGET_COPY_OUT_VENDOR)/dsp/cdsp/fastrpc_shell_unsigned_3

# Include vibrator configuration files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/etc/vibrator_service_config:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator_service_config \
    vendor/oneplus/giulia/proprietary/vendor/etc/vibrator/vibrator_customized_effect.json:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/vibrator_customized_effect.json \
    vendor/oneplus/giulia/proprietary/vendor/etc/vibrator/vibrator_effect.json:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/vibrator_effect.json \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vibrator-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vibrator-default.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/init/vibrator-default.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vibrator-default.rc

# Additional modules or packages specific to this device
PRODUCT_PACKAGES += \
    CACertService \
    CneApp \
    IWlanService \
    TimeService \
    TrustZoneAccessService

# Vibrator and fingerprint libraries
PRODUCT_PACKAGES += \
    android.hardware.vibrator-V2-ndk \
    libaacvibrator \
    liboplusvibratoreffect \
    vendor.oplus.hardware.vibrator-V1-ndk \
    vendor.oplus.hardware.biometrics.fingerprint \
    libudfps_extension.oneplus

# Add proprietary permissions
PRODUCT_COPY_FILES += \
    frameworks/native/data/etc/android.hardware.biometrics.face.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.biometrics.face.xml \
    frameworks/native/data/etc/android.hardware.biometrics.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.biometrics.fingerprint.xml

# OnePlus 13R / Giulia device identifiers
PRODUCT_MODEL := CPH2691
PRODUCT_SYSTEM_NAME := OnePlus13R
PRODUCT_SYSTEM_DEVICE := OP5D3BL1
PRODUCT_GMS_CLIENTID_BASE := android-oneplus

# Device-specific properties
PRODUCT_PROPERTY_OVERRIDES += \
    ro.vendor.build.fingerprint=OnePlus/CPH2691IN/OP5D3BL1:15/UKQ1.231108.001/V.R4T3.1cff019-3eb5-3eb4:user/release-keys \
    ro.product.vendor.brand=oneplus \
    ro.product.vendor.device=giulia \
    ro.product.vendor.manufacturer=oneplus \
    ro.product.vendor.model=CPH2691 \
    ro.product.vendor.name=OnePlus13R \
    ro.product.board=pineapple \
    ro.soc.manufacturer=QTI

# Inherit from qcom common vendor - handles common QCOM components
$(call inherit-product, vendor/qcom/common/qcom-common.mk)

# Include product binaries
$(call inherit-product, vendor/oneplus/giulia/giulia-vendor-blobs.mk)

# Apps
PRODUCT_PACKAGES += \
    TimeService

# Include proprietary files
include vendor/oneplus/giulia/proprietary/vendor/build/vendor-board.mk
include vendor/oneplus/giulia/proprietary/odm/build/odm-board.mk

# Prebuilt APKs
PRODUCT_PACKAGES += \
    IWlanService \
    qcrilmsgtunnel

# Vendor libraries
PRODUCT_PACKAGES += \
    libQnnHtp \
    libQnnSystem \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.7 \
    vendor.qti.hardware.radio.ims@1.9 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.perf@2.3 \
    vendor.qti.hardware.bluetooth_audio@2.1 \
    vendor.oplus.hardware.charger@1.0 \
    vendor.oplus.hardware.performance@2.0

# Copy critical proprietary firmware and hardware-specific files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/alipay.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/alipay.mdt \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/fidotap.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/fidotap.b05

# Critical proprietary hardware components
PRODUCT_PACKAGES += \
    IWlanService \
    qcrilmsgtunnel

# Essential vendor libraries
PRODUCT_PACKAGES += \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.7 \
    vendor.qti.hardware.radio.ims@1.9 \
    vendor.oplus.hardware.charger@1.0 \
    vendor.oplus.hardware.biometrics.fingerprint

# Device identifiers
PRODUCT_MODEL := CPH2691
PRODUCT_SYSTEM_NAME := OnePlus13R
PRODUCT_SYSTEM_DEVICE := OP5D3BL1

# Include vendor blobs
$(call inherit-product, vendor/oneplus/giulia/giulia-vendor-blobs.mk) 