# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/giulia/setup-makefiles.sh

# Essential VINTF manifest files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.ir-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.ir-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/binaural_record.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/binaural_record.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/device_manifest_subsys.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/device_manifest_subsys.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_charger_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_charger_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_fingerprint_aidl_v3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_fingerprint_aidl_v3.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/nfc-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/nfc-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/secure_element-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/secure_element_omapi_service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element_omapi_service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vendor.qti.qegahal-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.qti.qegahal-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vibrator-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vibrator-default.xml

# Essential vendor binaries
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/bin/adsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/adsprpcd \
    vendor/oneplus/giulia/proprietary/vendor/bin/audioadsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/audioadsprpcd \
    vendor/oneplus/giulia/proprietary/vendor/bin/cdsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/cdsprpcd \
    vendor/oneplus/giulia/proprietary/vendor/bin/cnss-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/cnss-daemon \
    vendor/oneplus/giulia/proprietary/vendor/bin/dspservice:$(TARGET_COPY_OUT_VENDOR)/bin/dspservice \
    vendor/oneplus/giulia/proprietary/vendor/bin/ims_rtp_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/ims_rtp_daemon \
    vendor/oneplus/giulia/proprietary/vendor/bin/imsdaemon:$(TARGET_COPY_OUT_VENDOR)/bin/imsdaemon \
    vendor/oneplus/giulia/proprietary/vendor/bin/init.qcom.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qcom.sh

# Essential vendor apps
PRODUCT_PACKAGES += \
    IWlanService \
    TimeService

# Essential firmware files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b00 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b01 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b02 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b03 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b04 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b05 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b06 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b07 \
    vendor/oneplus/giulia/proprietary/vendor/firmware/firmware/cryptoeng.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/firmware/cryptoeng.b08

# Bluetooth firmware files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/firmware/bt_firmware/hmtbtfw10.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw10.tlv \
    vendor/oneplus/giulia/proprietary/vendor/firmware/bt_firmware/hmtbtfw10.ver:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw10.ver \
    vendor/oneplus/giulia/proprietary/vendor/firmware/bt_firmware/hmtbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw20.tlv \
    vendor/oneplus/giulia/proprietary/vendor/firmware/bt_firmware/hmtbtfw20.ver:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw20.ver \
    vendor/oneplus/giulia/proprietary/vendor/firmware/bt_firmware/hmtnv20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtnv20.bin

# DSP files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/dsp/adsp/fastrpc_shell_0:$(TARGET_COPY_OUT_VENDOR)/dsp/adsp/fastrpc_shell_0 \
    vendor/oneplus/giulia/proprietary/vendor/dsp/cdsp/fastrpc_shell_0:$(TARGET_COPY_OUT_VENDOR)/dsp/cdsp/fastrpc_shell_0

# Essential system libraries
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/system/lib64/libgui_vendor.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgui_vendor.so

# Critical proprietary camera models
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/blurDet_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/blurDet_sm8650.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin

# Copy all essential vendor files
$(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/firmware,$(TARGET_COPY_OUT_VENDOR)/firmware)
$(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/lib64,$(TARGET_COPY_OUT_VENDOR)/lib64)

# VINTF manifest files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.ir-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.ir-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/binaural_record.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/binaural_record.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/device_manifest_communication_center_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/device_manifest_communication_center_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/device_manifest_subsys.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/device_manifest_subsys.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_engineer_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_engineer_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_misc_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_misc_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplusSensor_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplusSensor_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_camera_rfi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_camera_rfi.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_cammidasservice_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_cammidasservice_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_cwb_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_cwb_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_displaypanelfeature_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_displaypanelfeature_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_eid.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_eid.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_esim.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_esim.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_face.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_face.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_fido.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_fido.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_fido2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_fido2.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_gameopt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_gameopt.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_ifaa.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_ifaa.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_keymint_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_keymint_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_location_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_location_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_nfcExtns.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_nfcExtns.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_riskdetect.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_riskdetect.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_sendextcamcmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_sendextcamcmd.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_stability_project_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_stability_project_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_virtualdevice_audio_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_virtualdevice_audio_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_oplus_weaver_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_weaver_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_performance_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_performance_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_powermonitor_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_powermonitor_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_rpmh_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_rpmh_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_touch_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_touch_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_transfer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_transfer.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/manifest_transmessage_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_transmessage_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/oplus_aidl_wifi_service_device_manifest.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/oplus_aidl_wifi_service_device_manifest.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/secure_element-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/secure_element_omapi_service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element_omapi_service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vendor.oplus.camera.aon-impl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.oplus.camera.aon-impl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vendor.oplus.hardware.olc2_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.oplus.hardware.olc2_aidl.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vendor.oplus.hardware.urcc-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.oplus.hardware.urcc-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vendor.qti.qegahal-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.qti.qegahal-service.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vibrator-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vibrator-default.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/manifest/vintf_manifext_aidl_panelchaplin.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vintf_manifext_aidl_panelchaplin.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/telephony_manifest_dsds.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/telephony_manifest_dsds.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/telephony_manifest_ssss.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/telephony_manifest_ssss.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/network_manifest_dsds.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/network_manifest_dsds.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/vintf/network_manifest_ssss.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/network_manifest_ssss.xml

# Add new vendor files
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/vendor/etc/wifi/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wifi.cfg \
    vendor/oneplus/giulia/proprietary/vendor/etc/wifi/cnss_diag.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/cnss_diag.conf \
    vendor/oneplus/giulia/proprietary/vendor/etc/wifi/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/regdb.bin \
    vendor/oneplus/giulia/proprietary/vendor/etc/bluetooth.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth.cfg \
    vendor/oneplus/giulia/proprietary/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/virtual_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual_audio_policy_configuration.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/binaural_record_algo_coeffs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/binaural_record_algo_coeffs.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/media_codecs_dolby_vision.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_vision.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/media_codecs_vendor_oplus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_vendor_oplus.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/sensor.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/sensor.cfg \
    vendor/oneplus/giulia/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/oneplus/giulia/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/oneplus/giulia/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/oneplus/giulia/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/oneplus/giulia/proprietary/vendor/etc/power_stats_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_stats_config.xml \
    vendor/oneplus/giulia/proprietary/vendor/etc/resourcemanager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/resourcemanager.xml

# Display configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/etc/display/,$(TARGET_COPY_OUT_VENDOR)/etc/display)

# Sensor configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/etc/sensor/,$(TARGET_COPY_OUT_VENDOR)/etc/sensor)

# Audio configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/etc/audio/,$(TARGET_COPY_OUT_VENDOR)/etc/audio)

# NFC configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/etc/nfc/,$(TARGET_COPY_OUT_VENDOR)/etc/nfc)

# Bluetooth configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/etc/bt/,$(TARGET_COPY_OUT_VENDOR)/etc/bt) 