# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/giulia/setup-makefiles.sh

# Essential proprietary system libraries
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/system/lib64/libgui_vendor.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgui_vendor.so

# Critical proprietary camera models
PRODUCT_COPY_FILES += \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/blurDet_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/blurDet_sm8650.bin \
    vendor/oneplus/giulia/proprietary/odm/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin

# Copy all essential vendor files
$(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/firmware,$(TARGET_COPY_OUT_VENDOR)/firmware)
$(call find-copy-subdir-files,*,vendor/oneplus/giulia/proprietary/vendor/lib64,$(TARGET_COPY_OUT_VENDOR)/lib64) 