# Copyright (C) 2024 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oneplus/giulia/setup-makefiles.sh

# Define base paths
VENDOR_PATH := vendor/oneplus/giulia/proprietary

# Essential vendor binaries
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/bin/adsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/adsprpcd \
    $(VENDOR_PATH)/vendor/bin/audioadsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/audioadsprpcd \
    $(VENDOR_PATH)/vendor/bin/cdsprpcd:$(TARGET_COPY_OUT_VENDOR)/bin/cdsprpcd \
    $(VENDOR_PATH)/vendor/bin/cnss-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/cnss-daemon \
    $(VENDOR_PATH)/vendor/bin/ims_rtp_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/ims_rtp_daemon \
    $(VENDOR_PATH)/vendor/bin/imsdaemon:$(TARGET_COPY_OUT_VENDOR)/bin/imsdaemon \
    $(VENDOR_PATH)/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/audio,$(TARGET_COPY_OUT_VENDOR)/etc/audio)

# Hardware HAL Services
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/bin/hw/android.hardware.audio.service_64:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.audio.service_64 \
    $(VENDOR_PATH)/vendor/bin/hw/android.hardware.bluetooth@1.1-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.bluetooth@1.1-service-qti \
    $(VENDOR_PATH)/vendor/bin/hw/android.hardware.gatekeeper-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gatekeeper-service-qti \
    $(VENDOR_PATH)/vendor/bin/hw/android.hardware.keymaster@4.0-service-qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.keymaster@4.0-service-qti \
    $(VENDOR_PATH)/vendor/bin/hw/android.hardware.sensors-service.multihal:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.sensors-service.multihal

# Camera HAL and configurations
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/bin/hw/vendor.qti.camera.provider-service_64:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.camera.provider-service_64 \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/camera,$(TARGET_COPY_OUT_ODM)/etc/camera)

# Audio configurations
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    $(VENDOR_PATH)/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    $(VENDOR_PATH)/vendor/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/audio,$(TARGET_COPY_OUT_VENDOR)/etc/audio)

# Configuration files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/etc/bluetooth.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth.cfg \
    $(VENDOR_PATH)/vendor/etc/sensor.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/sensor.cfg \
    $(VENDOR_PATH)/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    $(VENDOR_PATH)/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    $(VENDOR_PATH)/vendor/etc/power_stats_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_stats_config.xml \
    $(VENDOR_PATH)/vendor/etc/resourcemanager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/resourcemanager.xml

# Firmware files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/firmware,$(TARGET_COPY_OUT_VENDOR)/firmware)

# System libraries
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/lib64,$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64)

# Display configurations
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/display,$(TARGET_COPY_OUT_VENDOR)/etc/display)

# Sensor configurations
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/sensor,$(TARGET_COPY_OUT_VENDOR)/etc/sensor)

# DSP files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/dsp/adsp,$(TARGET_COPY_OUT_VENDOR)/dsp/adsp) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/dsp/cdsp,$(TARGET_COPY_OUT_VENDOR)/dsp/cdsp)

# Essential VINTF manifest files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.ir-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.ir-service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/binaural_record.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/binaural_record.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/device_manifest_subsys.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/device_manifest_subsys.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/secure_element-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element-service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/secure_element_omapi_service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element_omapi_service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/vibrator-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vibrator-default.xml

# Additional vendor files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/lib64,$(TARGET_COPY_OUT_VENDOR)/lib64)

# Firmware files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/firmware/sipa.bin:$(TARGET_COPY_OUT_ODM)/firmware/sipa.bin \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/firmware/fastchg,$(TARGET_COPY_OUT_ODM)/firmware/fastchg) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/firmware/tp,$(TARGET_COPY_OUT_ODM)/firmware/tp) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/firmware/ufs,$(TARGET_COPY_OUT_ODM)/firmware/ufs)

# Feature-specific packages
PRODUCT_PACKAGES += \
    IWlanService \
    TimeService

# Inherit vendor properties
-include $(VENDOR_PATH)/vendor.prop

# Remove firmware files that don't exist
# cryptoeng.b* and uff_spi.b* files are removed as they are not present in the source
# If these files are essential, they need to be obtained from another source

# Bluetooth firmware files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/firmware/bt_firmware/hmtbtfw10.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw10.tlv \
    $(VENDOR_PATH)/vendor/firmware/bt_firmware/hmtbtfw10.ver:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw10.ver \
    $(VENDOR_PATH)/vendor/firmware/bt_firmware/hmtbtfw20.tlv:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw20.tlv \
    $(VENDOR_PATH)/vendor/firmware/bt_firmware/hmtbtfw20.ver:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtbtfw20.ver \
    $(VENDOR_PATH)/vendor/firmware/bt_firmware/hmtnv20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bt_firmware/hmtnv20.bin

# Note: The following firmware files are missing and need to be obtained from the device:
# - cryptoeng.b00 through cryptoeng.b08
# - uff_spi.b00 through uff_spi.b08
# These files should be placed in vendor/firmware/firmware/ once obtained

# Essential system libraries
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/system/lib64/libgui_vendor.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libgui_vendor.so

# Critical proprietary camera models
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/etc/camera/aigc/aigc_models/blurDet_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/blurDet_sm8650.bin \
    $(VENDOR_PATH)/odm/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin:$(TARGET_COPY_OUT_ODM)/etc/camera/aigc/aigc_models/faceSeg_sm8650.bin

# Copy all essential vendor files
$(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/firmware,$(TARGET_COPY_OUT_VENDOR)/firmware)
$(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/lib64,$(TARGET_COPY_OUT_VENDOR)/lib64)

# VINTF manifest files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.contexthub-service.qmi.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.ir-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.ir-service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.power.stats-service.oplus.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.power.stats.IPowerStats-V2.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.keymint-service.strongbox.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.security.sharedsecret-service.strongbox.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/android.hardware.weaver-service.nxp.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/binaural_record.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/binaural_record.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/device_manifest_communication_center_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/device_manifest_communication_center_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/device_manifest_subsys.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/device_manifest_subsys.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_engineer_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_engineer_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_misc_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_misc_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplusSensor_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplusSensor_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_camera_rfi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_camera_rfi.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_cammidasservice_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_cammidasservice_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_cwb_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_cwb_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_displaypanelfeature_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_displaypanelfeature_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_eid.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_eid.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_esim.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_esim.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_face.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_face.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_fido.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_fido.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_fido2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_fido2.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_gameopt.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_gameopt.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_ifaa.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_ifaa.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_keymint_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_keymint_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_location_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_location_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_nfcExtns.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_nfcExtns.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_riskdetect.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_riskdetect.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_sendextcamcmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_sendextcamcmd.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_stability_project_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_stability_project_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_virtualdevice_audio_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_virtualdevice_audio_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_oplus_weaver_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_oplus_weaver_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_performance_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_performance_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_powermonitor_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_powermonitor_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_rpmh_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_rpmh_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_touch_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_touch_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_transfer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_transfer.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/manifest_transmessage_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/manifest_transmessage_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/oplus_aidl_wifi_service_device_manifest.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/oplus_aidl_wifi_service_device_manifest.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/secure_element-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element-service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/secure_element_omapi_service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/secure_element_omapi_service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/vendor.oplus.camera.aon-impl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.oplus.camera.aon-impl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/vendor.oplus.hardware.olc2_aidl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.oplus.hardware.olc2_aidl.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/vendor.oplus.hardware.urcc-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.oplus.hardware.urcc-service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/vendor.qti.qegahal-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.qti.qegahal-service.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/vibrator-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vibrator-default.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/manifest/vintf_manifext_aidl_panelchaplin.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vintf_manifext_aidl_panelchaplin.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/telephony_manifest_dsds.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/telephony_manifest_dsds.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/telephony_manifest_ssss.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/telephony_manifest_ssss.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/network_manifest_dsds.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/network_manifest_dsds.xml \
    $(VENDOR_PATH)/vendor/etc/vintf/network_manifest_ssss.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/network_manifest_ssss.xml

# Add new vendor files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/etc/wifi/wifi.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wifi.cfg \
    $(VENDOR_PATH)/vendor/etc/wifi/cnss_diag.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/cnss_diag.conf \
    $(VENDOR_PATH)/vendor/etc/wifi/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/regdb.bin \
    $(VENDOR_PATH)/vendor/etc/virtual_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual_audio_policy_configuration.xml \
    $(VENDOR_PATH)/vendor/etc/binaural_record_algo_coeffs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/binaural_record_algo_coeffs.xml \
    $(VENDOR_PATH)/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    $(VENDOR_PATH)/vendor/etc/media_codecs_dolby_vision.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_vision.xml \
    $(VENDOR_PATH)/vendor/etc/media_codecs_vendor_oplus.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_vendor_oplus.xml \
    $(VENDOR_PATH)/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    $(VENDOR_PATH)/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    $(VENDOR_PATH)/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    $(VENDOR_PATH)/vendor/etc/power_stats_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_stats_config.xml

# Display configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/display,$(TARGET_COPY_OUT_VENDOR)/etc/display)

# Sensor configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/sensor,$(TARGET_COPY_OUT_VENDOR)/etc/sensor)

# Audio configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/audio,$(TARGET_COPY_OUT_VENDOR)/etc/audio)

# NFC configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/nfc,$(TARGET_COPY_OUT_VENDOR)/etc/nfc)

# Bluetooth configs
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/etc/bt,$(TARGET_COPY_OUT_VENDOR)/etc/bt)

# Additional audio components
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/etc,$(TARGET_COPY_OUT_PRODUCT)/etc) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/lib64/soundfx,$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/soundfx)

# Additional media components
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/lib64,$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/bin/hw,$(TARGET_COPY_OUT_VENDOR)/bin/hw)

# DRM and crypto components
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/lib64,$(TARGET_COPY_OUT_ODM)/lib64) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/vendor/apex,$(TARGET_COPY_OUT_VENDOR)/apex)

# Additional configuration files
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/vendor/etc,$(TARGET_COPY_OUT_VENDOR)/etc) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/etc,$(TARGET_COPY_OUT_SYSTEM_EXT)/etc)

# Additional configuration and XML files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/etc/binaural_record_algo_coeffs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/binaural_record_algo_coeffs.xml \
    $(VENDOR_PATH)/odm/etc/mixer_paths.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mixer_paths.xml \
    $(VENDOR_PATH)/odm/etc/resourcemanager.xml:$(TARGET_COPY_OUT_VENDOR)/etc/resourcemanager.xml \
    $(VENDOR_PATH)/odm/etc/virtual_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual_audio_policy_configuration.xml \
    $(VENDOR_PATH)/odm/etc/bluetooth.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth.cfg \
    $(VENDOR_PATH)/odm/etc/power_stats_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_stats_config.xml \
    $(VENDOR_PATH)/odm/etc/sensor.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/sensor.cfg

# Additional Essential Vendor Binaries
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/bin/ATFWD-daemon:$(TARGET_COPY_OUT_VENDOR)/bin/ATFWD-daemon \
    $(VENDOR_PATH)/vendor/bin/cnd:$(TARGET_COPY_OUT_VENDOR)/bin/cnd \
    $(VENDOR_PATH)/vendor/bin/diag_mdlog:$(TARGET_COPY_OUT_VENDOR)/bin/diag_mdlog \
    $(VENDOR_PATH)/vendor/bin/dpmQmiMgr:$(TARGET_COPY_OUT_VENDOR)/bin/dpmQmiMgr \
    $(VENDOR_PATH)/vendor/bin/feature_enabler_client:$(TARGET_COPY_OUT_VENDOR)/bin/feature_enabler_client \
    $(VENDOR_PATH)/vendor/bin/hal_proxy_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/hal_proxy_daemon \
    $(VENDOR_PATH)/vendor/bin/hexlpservice:$(TARGET_COPY_OUT_VENDOR)/bin/hexlpservice

# Additional Hardware HAL Services
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/bin/hw/vendor.qti.hardware.alarm-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.hardware.alarm-service \
    $(VENDOR_PATH)/vendor/bin/hw/vendor.qti.hardware.display.composer-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.hardware.display.composer-service \
    $(VENDOR_PATH)/vendor/bin/hw/android.hardware.health-service.qti:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.health-service.qti \
    $(VENDOR_PATH)/vendor/bin/hw/vendor.qti.hardware.lights.service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.hardware.lights.service \
    $(VENDOR_PATH)/vendor/bin/hw/vendor.qti.media.c2@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.media.c2@1.0-service

# Essential Init Scripts
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/vendor/bin/init.qcom.usb.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qcom.usb.sh \
    $(VENDOR_PATH)/vendor/bin/init.qcom.class_core.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qcom.class_core.sh \
    $(VENDOR_PATH)/vendor/bin/init.qcom.sensors.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qcom.sensors.sh \
    $(VENDOR_PATH)/vendor/bin/init.qti.display_boot.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.qti.display_boot.sh

# System Extension Components
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/lib64,$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/framework,$(TARGET_COPY_OUT_SYSTEM_EXT)/framework) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/etc,$(TARGET_COPY_OUT_SYSTEM_EXT)/etc)

# OnePlus specific components
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/oplus,$(TARGET_COPY_OUT_SYSTEM_EXT)/oplus) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/system_ext/oplusex,$(TARGET_COPY_OUT_SYSTEM_EXT)/oplusex)

# ODM RC Files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/init.oplus.face.rc:$(TARGET_COPY_OUT_ODM)/init.oplus.face.rc \
    $(VENDOR_PATH)/odm/init.oplus.seccommon.rc:$(TARGET_COPY_OUT_ODM)/init.oplus.seccommon.rc

# ODM Configuration Files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/etc/audio.cfg:$(TARGET_COPY_OUT_ODM)/etc/audio.cfg \
    $(VENDOR_PATH)/odm/etc/backend_conf.xml:$(TARGET_COPY_OUT_ODM)/etc/backend_conf.xml \
    $(VENDOR_PATH)/odm/etc/charge.cfg:$(TARGET_COPY_OUT_ODM)/etc/charge.cfg \
    $(VENDOR_PATH)/odm/etc/custom_power.cfg:$(TARGET_COPY_OUT_ODM)/etc/custom_power.cfg \
    $(VENDOR_PATH)/odm/etc/displaycolorfeaturecfg.xml:$(TARGET_COPY_OUT_ODM)/etc/displaycolorfeaturecfg.xml \
    $(VENDOR_PATH)/odm/etc/ftm_mixer_paths.xml:$(TARGET_COPY_OUT_ODM)/etc/ftm_mixer_paths.xml \
    $(VENDOR_PATH)/odm/etc/gps_modem.cfg:$(TARGET_COPY_OUT_ODM)/etc/gps_modem.cfg

# ODM Modem Configurations
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/etc/modem_custom.cfg:$(TARGET_COPY_OUT_ODM)/etc/modem_custom.cfg \
    $(VENDOR_PATH)/odm/etc/modem_data.cfg:$(TARGET_COPY_OUT_ODM)/etc/modem_data.cfg \
    $(VENDOR_PATH)/odm/etc/modem_rf.cfg:$(TARGET_COPY_OUT_ODM)/etc/modem_rf.cfg \
    $(VENDOR_PATH)/odm/etc/modem_simcard.cfg:$(TARGET_COPY_OUT_ODM)/etc/modem_simcard.cfg \
    $(VENDOR_PATH)/odm/etc/modem_voice.cfg:$(TARGET_COPY_OUT_ODM)/etc/modem_voice.cfg

# ODM Display Configurations
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/etc/p_3_a0020_backlight_data.xml:$(TARGET_COPY_OUT_ODM)/etc/p_3_a0020_backlight_data.xml \
    $(VENDOR_PATH)/odm/etc/p_3_a0020_cinema_eyeprotect_data.xml:$(TARGET_COPY_OUT_ODM)/etc/p_3_a0020_cinema_eyeprotect_data.xml \
    $(VENDOR_PATH)/odm/etc/p_3_a0020_colorful_eyeprotect_datav.xml:$(TARGET_COPY_OUT_ODM)/etc/p_3_a0020_colorful_eyeprotect_datav.xml \
    $(VENDOR_PATH)/odm/etc/p_3_a0020_eyeprotect_data.xml:$(TARGET_COPY_OUT_ODM)/etc/p_3_a0020_eyeprotect_data.xml \
    $(VENDOR_PATH)/odm/etc/p_3_a0020_srgb_eyeprotect_data.xml:$(TARGET_COPY_OUT_ODM)/etc/p_3_a0020_srgb_eyeprotect_data.xml

# ODM Directory Copies
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/acdbdata,$(TARGET_COPY_OUT_ODM)/etc/acdbdata) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/camera,$(TARGET_COPY_OUT_ODM)/etc/camera) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/dolby,$(TARGET_COPY_OUT_ODM)/etc/dolby) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/init,$(TARGET_COPY_OUT_ODM)/etc/init) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/sensor,$(TARGET_COPY_OUT_ODM)/etc/sensor) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/wifi,$(TARGET_COPY_OUT_ODM)/etc/wifi)

# My Product Components
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/app,$(TARGET_COPY_OUT_PRODUCT)/app) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/etc,$(TARGET_COPY_OUT_PRODUCT)/etc) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/framework,$(TARGET_COPY_OUT_PRODUCT)/framework) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/lib,$(TARGET_COPY_OUT_PRODUCT)/lib) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/lib64,$(TARGET_COPY_OUT_PRODUCT)/lib64) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/overlay,$(TARGET_COPY_OUT_PRODUCT)/overlay) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/media,$(TARGET_COPY_OUT_PRODUCT)/media)

# OnePlus Custom Resources
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/cust,$(TARGET_COPY_OUT_PRODUCT)/cust) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/decouping_wallpaper,$(TARGET_COPY_OUT_PRODUCT)/decouping_wallpaper)

# OnePlus Product Overlays
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/my_product/product_overlay,$(TARGET_COPY_OUT_PRODUCT)/product_overlay)

# Firmware Configuration Files
PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/odm/etc/bsp_storage_core_config_update.xml:$(TARGET_COPY_OUT_ODM)/etc/bsp_storage_core_config_update.xml \
    $(VENDOR_PATH)/odm/etc/hal_uuid_map_15.xml:$(TARGET_COPY_OUT_ODM)/etc/hal_uuid_map_15.xml \
    $(VENDOR_PATH)/odm/etc/hal_uuid_map_7.xml:$(TARGET_COPY_OUT_ODM)/etc/hal_uuid_map_7.xml \
    $(VENDOR_PATH)/odm/etc/hal_uuid_map_config.xml:$(TARGET_COPY_OUT_ODM)/etc/hal_uuid_map_config.xml \
    $(VENDOR_PATH)/odm/etc/lra_model_0.conf:$(TARGET_COPY_OUT_ODM)/etc/lra_model_0.conf

# Firmware Permissions and SELinux
PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/selinux,$(TARGET_COPY_OUT_ODM)/etc/selinux) \
    $(call find-copy-subdir-files,*,$(VENDOR_PATH)/odm/etc/permissions,$(TARGET_COPY_OUT_ODM)/etc/permissions) 